# Usage

In [1]:
import os
from dotenv import load_dotenv
from openbb import obb

if 'info' in obb.reference:
    obj = obb.reference["info"]["extensions"]["openbb_provider_extension"]
    print([item for item in obj if "akshare" in item])
    print([item for item in obj if "tushare" in item])
    print([item for item in obj if "tdxquant" in item])

symbols = "601919,600519,000001,00300"
symbols_a = "601919,600519,000001,600325,600028,600036,430047"
symbol_a = "600325"
symbol_hk = "01658"
default_provider = "tdxquant"

os.environ["AKSHARE_API_KEY"] = obb.user.credentials.akshare_api_key.get_secret_value()
os.environ["TUSHARE_API_KEY"] = obb.user.credentials.tushare_api_key.get_secret_value()

#load_dotenv() 
akshare_api_key = os.environ.get("AKSHARE_API_KEY")
if akshare_api_key is None or akshare_api_key == "":
    raise ValueError("AKSHARE_API_KEY environment variable not set.")

tushare_api_key = os.environ.get("TUSHARE_API_KEY")
if tushare_api_key is None or tushare_api_key == "":
    raise ValueError("TUSHARE_API_KEY environment variable not set.")

['akshare@1.1.3']
['tushare@1.0.0']
['tdxquant@1.0.1']

In [3]:
from openbb import obb
from openbb_core.app.service.user_service import UserService
 
# 方式1：通过 UserService 修改
user_service = UserService()
user_settings = user_service.read_from_file()
default_provider = "tdxquant"
 
# 设置某个路由的默认提供者
user_settings.defaults.commands.update({
    "equity.price.historical": {
        "provider": default_provider
    },
    "equity.price.quote": {
        "provider": default_provider
    },
    "equity.search": {
        "provider": default_provider
    },
    "equity.fundamental.metrics": {
        "provider": default_provider
    },
    "obb.equity.profile": {
        "provider": default_provider
    }
})
 
# 保存到文件
UserService.write_to_file(user_settings)

In [ ]:
obb.user.credentials.tushare_api_key="dummy_key"
from openbb_core.app.service.user_service import UserService
u = UserService.read_from_file()
u.credentials.tushare_api_key="dummy_key"
UserService.write_to_file(u)

In [ ]:
from openbb_core.app.service.user_service import UserService
from pathlib import Path
 
# 读取用户设置
settings = UserService.read_from_file()
cache_dir = Path(settings.preferences.cache_directory)
 
# 在数据目录下创建SQLite数据库
db_path = cache_dir / "appdata/equity.db"
#conn = sqlite3.connect(db_path)

In [2]:
from openbb_app import project_name
print(project_name)

openbb_app

## Equity histrical price

In [2]:
obb.equity.price.historical(symbol="600325", use_cache=True, start_date="2026-01-01",end_date="2026-03-08").to_dataframe().tail()

2026-04-21 12:52:24,023 - openbb_tdx.utils.helpers - WARNING - Cache for 600325 is not up-to-date. Last date in cache: NaT, expected: 2026-04-20.

TQ数据接口初始化成功，使用路径: c:\Users\roger\src\finanalyzer\openbb-app\.venv\Lib\site-packages\openbb_tdx\utils\helpers.py

2026-04-21 12:52:29,416 - openbb_tdx.utils.helpers - INFO - Getting equity 600325 historical data from cache...

TQ数据连接已关闭

,open,high,low,close,volume,amount,change,change_percent
date,,,,,,,,
2026-03-02,4.27,4.35,4.21,4.29,68826368.0,29469.78,-0.02,-0.464037
2026-03-03,4.30,4.32,4.11,4.14,79248864.0,33189.81,-0.15,-3.496503
2026-03-04,4.10,4.17,4.05,4.09,44675104.0,18344.50,-0.05,-1.207729
2026-03-05,4.13,4.16,4.07,4.10,41824880.0,17121.88,0.01,0.244499
2026-03-06,4.08,4.14,4.07,4.13,39824000.0,16340.81,0.03,0.731707

## Equity Search (股票搜索)

In [2]:
symbol_b="00144"
result = obb.equity.search(query=symbol_b, provider=default_provider).to_dataframe()
result[result['symbol'] == symbol_b]

2026-04-21 18:02:15,519 - openbb_tdx.utils.tdx_equity_search - INFO - Loading symbols from openbb_tdx cache...
2026-04-21 18:02:15,724 - openbb_tdx.models.equity_search - INFO - Searching for 00144 and found 2 results.

  symbol   name exchange
1  00144  招商局港口     HKEX

## Equity Key Metrics

In [10]:
symbol_f="600325"
obb.equity.fundamental.metrics(symbol=symbol_f, provider=default_provider).to_dataframe().T

TQ数据连接已关闭

                                       0
symbol                            600325
period_ending                 2025-10-31
fiscal_year                         2025
fiscal_period                         Q4
currency                             CNY
market_cap                 98530000000.0
pe_ratio                          -34.87
forward_pe                         72.23
eps                                 0.05
price_to_sales              19039.521548
price_to_book                       0.52
book_value_per_share                 6.9
price_to_cash               28407.007145
cash_per_share                 12.602902
debt_to_equity                   8.30753
quick_ratio                     0.657469
current_ratio                   2.089729
gross_margin                    0.142574
profit_margin                     0.0054
operating_margin                0.034504
return_on_assets                0.000255
return_on_equity                 0.00539
dividend_yield                    0.0346
enterprise_value      98542300535.589996
ev_to_sales                 19041.898452
beta                                1.74
year_high                           5.74
year_low                            3.35
working_capital               17183982.0
total_debt                    15769046.0
operating_cash_flow           1741594.63
ebit_margin                     0.033719

## Equity profile

In [9]:
obb.equity.profile(symbol="600325", use_cache=True, provider=default_provider).to_dataframe().tail()

,symbol,name,hq_state,employees,sector,listed_date,total_assets,total_liabilities,revenue,net_income,...,J_mggjj,J_mgjzc2,J_gdqyb,J_gdrs,J_HalfYearFlag,tdx_dycode,rs_hycode_sim,blockzscode,underly_setcode,underly_code
0,600325,华发股份,广东板块,275215,房地产开发,2004-02-25,32953028.0,1898163.0,5175025.0,10230.35,...,0.41,6.90,0.06,50566.00,9,12,X5301,881418,0,

## Equity Quote (股票实时报价)

In [3]:
obb.equity.price.quote(symbols, provider=default_provider).to_dataframe().head()

TQ数据接口初始化成功，使用路径: c:\Users\roger\src\finanalyzer\openbb-app\.venv\Lib\site-packages\openbb_tdx\models\equity_quote.py

2026-04-21 18:02:29,071 - openbb_tdx.utils.tdx_equity_search - INFO - Loading symbols from openbb_tdx cache...

,symbol,name,exchange,bid,bid_size,ask,ask_size,market_center,last_price,last_size,...,high,low,close,volume,exchange_volume,prev_close,change,change_percent,year_high,year_low
0,601919,中远海控,上海交易所,14.62,1766,14.63,150,TdxQuant,14.62,5526,...,14.68,14.54,14.62,608762,608762,14.58,-0.02,-0.06,16.98,12.55
1,600519,贵州茅台,上海交易所,1412.01,65,1412.02,14,TdxQuant,1412.01,372,...,1419.90,1410.00,1412.01,21754,21754,1410.89,-1.49,-0.07,1593.37,1322.01
2,000001,平安银行,深圳交易所,11.08,1690,11.09,509,TdxQuant,11.08,7368,...,11.16,11.03,11.08,806946,806946,11.06,0.00,-0.08,13.09,10.29
3,00300,美的集团,香港交易所,0.00,0,0.00,0,TdxQuant,90.95,282100,...,91.80,89.50,90.95,2280920,2280920,90.30,0.00,0.06,0.00,0.00

## Equity Data

In [5]:
from openbb_app.core.equity_data import EquityData
equity_data = EquityData()

In [7]:
from IPython.display import HTML, display
display(HTML(equity_data.get_screener(is_realized=True, market='HK')))

2026-04-21 18:04:43,623 - openbb_app.core.equity_data - INFO - Calling get_screener with is_realized=True, market=HK
2026-04-21 18:04:43,627 - openbb_app.core.equity_data - INFO - Fetching current prices from provider with is_realized=True: 00123,00144,00386,00728,00939,00998,01288,01339,01398,01658,01919,02800,02880,03988,06823
2026-04-21 18:04:43,628 - openbb_app.core.utils - INFO - Fetching quote data for 00123
2026-04-21 18:04:43,654 - openbb_app.core.utils - INFO - Successfully fetched quote data for 00123
2026-04-21 18:04:43,655 - openbb_app.core.utils - INFO - Fetching quote data for 00144
2026-04-21 18:04:43,681 - openbb_app.core.utils - INFO - Successfully fetched quote data for 00144
2026-04-21 18:04:43,682 - openbb_app.core.utils - INFO - Fetching quote data for 00386
2026-04-21 18:04:43,713 - openbb_app.core.utils - INFO - Successfully fetched quote data for 00386
2026-04-21 18:04:43,714 - openbb_app.core.utils - INFO - Fetching quote data for 00728
2026-04-21 18:04:43,741 - openbb_app.core.utils - INFO - Successfully fetched quote data for 00728
2026-04-21 18:04:43,742 - openbb_app.core.utils - INFO - Fetching quote data for 00939
2026-04-21 18:04:43,771 - openbb_app.core.utils - INFO - Successfully fetched quote data for 00939
2026-04-21 18:04:43,772 - openbb_app.core.utils - INFO - Fetching quote data for 00998
2026-04-21 18:04:43,803 - openbb_app.core.utils - INFO - Successfully fetched quote data for 00998
2026-04-21 18:04:43,804 - openbb_app.core.utils - INFO - Fetching quote data for 01288
2026-04-21 18:04:43,828 - openbb_app.core.utils - INFO - Successfully fetched quote data for 01288
2026-04-21 18:04:43,829 - openbb_app.core.utils - INFO - Fetching quote data for 01339
2026-04-21 18:04:43,853 - openbb_app.core.utils - INFO - Successfully fetched quote data for 01339
2026-04-21 18:04:43,854 - openbb_app.core.utils - INFO - Fetching quote data for 01398
2026-04-21 18:04:43,879 - openbb_app.core.utils - INFO - Successfully fetched quote data for 01398
2026-04-21 18:04:43,880 - openbb_app.core.utils - INFO - Fetching quote data for 01658
2026-04-21 18:04:43,903 - openbb_app.core.utils - INFO - Successfully fetched quote data for 01658
2026-04-21 18:04:43,904 - openbb_app.core.utils - INFO - Fetching quote data for 01919
2026-04-21 18:04:43,928 - openbb_app.core.utils - INFO - Successfully fetched quote data for 01919
2026-04-21 18:04:43,929 - openbb_app.core.utils - INFO - Fetching quote data for 02800
2026-04-21 18:04:43,942 - openbb_tdx.models.equity_quote - ERROR - Error fetching data for symbol 02800: No data returned
2026-04-21 18:04:43,943 - openbb_tdx.models.equity_quote - WARNING - Skipping symbol 02800 due to error: No data returned
2026-04-21 18:04:43,944 - openbb_app.core.utils - ERROR - Error fetching quote data for 02800: Results not found.
2026-04-21 18:04:43,945 - openbb_app.core.utils - INFO - Fetching quote data for 02880
2026-04-21 18:04:43,970 - openbb_app.core.utils - INFO - Successfully fetched quote data for 02880
2026-04-21 18:04:43,970 - openbb_app.core.utils - INFO - Fetching quote data for 03988
2026-04-21 18:04:43,993 - openbb_app.core.utils - INFO - Successfully fetched quote data for 03988
2026-04-21 18:04:43,994 - openbb_app.core.utils - INFO - Fetching quote data for 06823
2026-04-21 18:04:44,017 - openbb_app.core.utils - INFO - Successfully fetched quote data for 06823

获取报表数据错误: server return none

## 自选股

In [2]:
from openbb_app.routes.portfolio import get_all_stocks

get_all_stocks()

2026-03-20 15:20:37,712 - openbb_app.routes.portfolio - INFO - Using cache directory: C:\Users\roger\OpenBBUserData\cache
2026-03-20 15:20:37,712 - openbb_app.core.database - INFO - Creating directory for database: C:\Users\roger\OpenBBUserData\cache\appdata
2026-03-20 15:20:37,715 - openbb_app.core.database - INFO - Directory created successfully: C:\Users\roger\OpenBBUserData\cache\appdata
2026-03-20 15:20:37,717 - openbb_app.core.utils - INFO - Fetching quote data for 600028.SH
2026-03-20 15:20:37,730 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600028
2026-03-20 15:20:38,594 - openbb_app.core.utils - INFO - Successfully fetched quote data for 600028.SH
2026-03-20 15:20:38,595 - openbb_app.core.utils - INFO - Fetching quote data for 600325.SH
2026-03-20 15:20:38,600 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600325
2026-03-20 15:20:39,517 - openbb_app.core.utils - INFO - Successfully fetched quote data for 600325.SH

[{'symbol': '600028.SH',
  'name': '中国石化',
  'avg_cost': 0.0,
  'quantity': 0,
  'total_value': 0.0,
  'current_price': 6.08,
  'fifty_two_week_low': 5.0466,
  'fifty_two_week_high': 8.11,
  'dividend_yield': 3.766,
  'latest_dividend': 0.229,
  'strategy': '持有',
  'tradingview': 'https://cn.tradingview.com/chart/?symbol=SSE:600028'},
 {'symbol': '600325.SH',
  'name': '华发股份',
  'avg_cost': 0.0,
  'quantity': 0,
  'total_value': 0.0,
  'current_price': 3.85,
  'fifty_two_week_low': 3.85,
  'fifty_two_week_high': 5.74,
  'dividend_yield': 3.221,
  'latest_dividend': 0.124,
  'strategy': '买进',
  'tradingview': 'https://cn.tradingview.com/chart/?symbol=SSE:600325'}]

In [2]:
from openbb_app.routes.portfolio import get_db_manager
db_manager = get_db_manager()

2026-03-20 15:53:28,343 - openbb_app.routes.portfolio - INFO - Using cache directory: C:\Users\roger\OpenBBUserData\cache
2026-03-20 15:53:28,343 - openbb_app.core.database - INFO - Creating directory for database: C:\Users\roger\OpenBBUserData\cache\appdata
2026-03-20 15:53:28,343 - openbb_app.core.database - INFO - Directory created successfully: C:\Users\roger\OpenBBUserData\cache\appdata

In [3]:
db_manager.get_all_portfolio_stocks()

2026-03-20 15:53:31,006 - openbb_app.core.utils - INFO - Fetching quote data for 600028.SH
2026-03-20 15:53:31,021 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600028
2026-03-20 15:53:31,918 - openbb_app.core.utils - INFO - Successfully fetched quote data for 600028.SH
2026-03-20 15:53:31,920 - openbb_app.core.utils - INFO - Fetching quote data for 600325.SH
2026-03-20 15:53:31,925 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600325
2026-03-20 15:53:32,759 - openbb_app.core.utils - INFO - Successfully fetched quote data for 600325.SH

[{'symbol': '600028.SH',
  'name': '中国石化',
  'avg_cost': 0.0,
  'quantity': 0,
  'total_value': 0.0,
  'current_price': 6.08,
  'fifty_two_week_low': 5.0466,
  'fifty_two_week_high': 8.11,
  'dividend_yield': 3.766,
  'latest_dividend': 0.229,
  'strategy': '持有',
  'tradingview': 'https://cn.tradingview.com/chart/?symbol=SSE:600028'},
 {'symbol': '600325.SH',
  'name': '华发股份',
  'avg_cost': 0.0,
  'quantity': 0,
  'total_value': 0.0,
  'current_price': 3.85,
  'fifty_two_week_low': 3.85,
  'fifty_two_week_high': 5.74,
  'dividend_yield': 3.221,
  'latest_dividend': 0.124,
  'strategy': '买进',
  'tradingview': 'https://cn.tradingview.com/chart/?symbol=SSE:600325'}]

In [4]:
db_manager.get_portfolio_stock("600325.SH")

2026-03-20 15:53:36,226 - openbb_app.core.utils - INFO - Fetching quote data for 600325.SH
2026-03-20 15:53:36,231 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600325
2026-03-20 15:53:37,124 - openbb_app.core.utils - INFO - Successfully fetched quote data for 600325.SH

{'symbol': '600325.SH',
 'name': '华发股份',
 'avg_cost': 0.0,
 'quantity': 0,
 'total_value': 0.0,
 'current_price': 3.85,
 'fifty_two_week_low': 3.85,
 'fifty_two_week_high': 5.74,
 'dividend_yield': 3.221,
 'latest_dividend': 0.124,
 'strategy': '买进',
 'tradingview': 'https://cn.tradingview.com/chart/?symbol=SSE:600325'}